# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'function_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(295, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Label_Tille = QtWidgets.QLabel(Dialog)
        self.Label_Tille.setObjectName("Label_Tille")
        self.verticalLayout.addWidget(self.Label_Tille)
        spacerItem1 = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Label_ID = QtWidgets.QLabel(Dialog)
        self.Label_ID.setObjectName("Label_ID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_ID)
        self.Label_full_name = QtWidgets.QLabel(Dialog)
        self.Label_full_name.setObjectName("Label_full_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_full_name)
        self.Label_DateOfBirth = QtWidgets.QLabel(Dialog)
        self.Label_DateOfBirth.setObjectName("Label_DateOfBirth")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_DateOfBirth)
        self.Label_Sex = QtWidgets.QLabel(Dialog)
        self.Label_Sex.setObjectName("Label_Sex")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_Sex)
        self.lineEdit_ID = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ID)
        self.lineEdit_fullName = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_fullName.setObjectName("lineEdit_fullName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_fullName)
        self.Label_class = QtWidgets.QLabel(Dialog)
        self.Label_class.setObjectName("Label_class")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_class)
        self.Label_GPA = QtWidgets.QLabel(Dialog)
        self.Label_GPA.setObjectName("Label_GPA")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_GPA)
        self.lineEdit_GPA = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_GPA.setObjectName("lineEdit_GPA")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_GPA)
        self.lineEdit_class = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_class.setObjectName("lineEdit_class")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_class)
        self.dateEdit_DateBirth = QtWidgets.QDateEdit(Dialog)
        self.dateEdit_DateBirth.setCalendarPopup(True)
        self.dateEdit_DateBirth.setObjectName("dateEdit_DateBirth")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit_DateBirth)
        self.comboBox_gender = QtWidgets.QComboBox(Dialog)
        self.comboBox_gender.setObjectName("comboBox_gender")
        self.comboBox_gender.addItem("")
        self.comboBox_gender.addItem("")
        self.comboBox_gender.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_gender)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_update_infor = QtWidgets.QPushButton(Dialog)
        self.btn_update_infor.setObjectName("btn_update_infor")
        self.horizontalLayout.addWidget(self.btn_update_infor)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Label_Tille.setText(_translate("Dialog", "Cập nhật sinh viên"))
        self.Label_ID.setText(_translate("Dialog", "Mã SV"))
        self.Label_full_name.setText(_translate("Dialog", "Họ tên"))
        self.Label_DateOfBirth.setText(_translate("Dialog", "Ngày sinh"))
        self.Label_Sex.setText(_translate("Dialog", "Giới tính"))
        self.Label_class.setText(_translate("Dialog", "Lớp"))
        self.Label_GPA.setText(_translate("Dialog", "GPA"))
        self.dateEdit_DateBirth.setDisplayFormat(_translate("Dialog", "dd/MM/yyyy"))
        self.comboBox_gender.setItemText(0, _translate("Dialog", "Nam"))
        self.comboBox_gender.setItemText(1, _translate("Dialog", "Nữ"))
        self.comboBox_gender.setItemText(2, _translate("Dialog", "Khác"))
        self.btn_cancel.setText(_translate("Dialog", "Hủy"))
        self.btn_update_infor.setText(_translate("Dialog", "Cập Nhật"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
